version: "3.3"
services:

  # backend:
  #   image: "videogame/backend"
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     DB_PASSWORD: mysecretpassword
  #     DB_USER: game
  #     DB_HOST: database
  #   command: bash -c "sleep 10 && node index.js"


  database:
    image: "postgres"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: game
      POSTGRES_DB: videogames
